In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
    
pd.set_option('display.max_columns', None)

In [3]:
# Load the CSV file",
file_path = './vahomehealthcare_facilities.csv'  # Update this path if your file is named differently\n",
df = pd.read_csv(file_path)
df.head()

,State,CMS Certification Number (CCN),Provider Name,Address,City/Town,ZIP Code,Telephone Number,Type of Ownership,Offers Nursing Care Services,Offers Physical Therapy Services,Offers Occupational Therapy Services,Offers Speech Pathology Services,Offers Medical Social Services,Offers Home Health Aide Services,Certification Date,Quality of patient care star rating,Footnote for quality of patient care star rating,Numerator for how often the home health team began their patients' care in a timely manner,Denominator for how often the home health team began their patients' care in a timely manner,How often the home health team began their patients' care in a timely manner,Footnote for how often the home health team began their patients' care in a timely manner,Numerator for how often the home health team determined whether patients received a flu shot for the current flu season,Denominator for how often the home health team determined whether patients received a flu shot for the current flu season,How often the home health team determined whether patients received a flu shot for the current flu season,Footnote for how often the home health team determined whether patients received a flu shot for the current flu season,Numerator for how often patients got better at walking or moving around,Denominator for how often patients got better at walking or moving around,How often patients got better at walking or moving around,Footnote for how often patients got better at walking or moving around,Numerator for how often patients got better at getting in and out of bed,Denominator for how often patients got better at getting in and out of bed,How often patients got better at getting in and out of bed,Footnote for how often patients got better at getting in and out of bed,Numerator for how often patients got better at bathing,Denominator for how often patients got better at bathing,How often patients got better at bathing,Footnote for how often patients got better at bathing,Numerator for how often patients' breathing improved,Denominator for how often patients' breathing improved,How often patients' breathing improved,Footnote for how often patients' breathing improved,Numerator for how often patients got better at taking their drugs correctly by mouth,Denominator for how often patients got better at taking their drugs correctly by mouth,How often patients got better at taking their drugs correctly by mouth,Footnote for how often patients got better at taking their drugs correctly by mouth,Numerator for Changes in skin integrity post-acute care: pressure ulcer/injury,Denominator for Changes in skin integrity post-acute care: pressure ulcer/injury,Changes in skin integrity post-acute care: pressure ulcer/injury,Footnote Changes in skin integrity post-acute care: pressure ulcer/injury,Numerator for how often physician-recommended actions to address medication issues were completely timely,Denominator for how often physician-recommended actions to address medication issues were completely timely,How often physician-recommended actions to address medication issues were completely timely,Footnote for how often physician-recommended actions to address medication issues were completely timely,Numerator for Percent of Residents Experiencing One or More Falls with Major Injury,Denominator for Percent of Residents Experiencing One or More Falls with Major Injury,Percent of Residents Experiencing One or More Falls with Major Injury,Footnote for Percent of Residents Experiencing One or More Falls with Major Injury,Numerator for Discharge Function Score,Denominator for Discharge Function Score,Discharge Function Score,Footnote for Discharge Function Score,Numerator for Transfer of Health Information to the Provider,Denominator for Transfer of Health Information to the Provider,Transfer of Health Information to the Provider,Footnote for Transfer of Health Information to the Provider,Numerator for Transfer of Health Information to the Patient,Denominator for Transfer of Health Information to the Patient,Transfer of Health Information to the Patient,Footnote for Transfer of Health Information to the Patient,DTC Numerator,DTC Denominator,DTC Observed Rate,DTC Risk-Standardized Rate,DTC Risk-Standardized Rate (Lower Limit),DTC Risk-Standardized Rate (Upper Limit),DTC Performance Categorization,Footnote for DTC Risk-Standardized Rate,PPR Numerator,PPR Denominator,PPR Observed Rate,PPR Risk-Standardized Rate,PPR Risk-Standardized Rate (Lower Limit),PPR Risk-Standardized Rate (Upper Limit),PPR Performance Categorization,Footnote for PPR Risk-Standardized Rate,PPH Numerator,PPH Denominator,PPH Observed Rate,PPH Risk-Standardized Rate,PPH Risk-Standardized Rate (Lower Limit),PPH Risk-Standardized Rate (Upper Limit),PPH Performance Categorization,Footnote for PPH Risk-Standardized Rate,"How much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally","Footnote for how much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally","No. of episodes to calc how much Medicare spends per episode of care at agency, compared to spending at all agencies (national)"
0,VA,497008,INOVA HOME HEALTH LLC,9900 MAIN STREET - SUITE 100,FAIRFAX,22031,5714323100,PROPRIETARY,Yes,Yes,Yes,Yes,No,Yes,10/01/1976,4,-,"4,046","4,492",90.1,-,"1,712","2,774",61.7,-,"3,015","3,230",91.8,-,"3,066","3,221",93.6,-,"3,098","3,228",94.4,-,"1,890","1,943",98.8,-,"3,026","3,189",92.2,-,3,"3,341",0.2,-,"3,959","4,495",88.1,-,22,"4,464",0.5,-,"2,173","3,227",67.34,-,212,270,78.52,-,"2,546","3,071",82.90,-,"2,851","4,299",66.32,71.48,69.69,72.96,Worse Than National Rate,-,98,"3,359",2.92,3.36,2.85,3.90,Same As National Rate,-,240,"1,843",13.02,10.76,9.57,11.78,Same As National Rate,-,0.98,-,"6,276"
1,VA,497015,FAMILY CARE SENIOR SOLUTIONS,801 COURT STREET,PORTSMOUTH,23704,7573999700,PROPRIETARY,Yes,Yes,Yes,Yes,No,Yes,05/30/1985,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,1,20,5.00,3.89,2.58,5.61,Same As National Rate,-,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,This measure currently does not have data or p...,-
2,VA,497018,CARILION HOME CARE SERVICES TAZEWELL,388 BEN BOLT AVENUE,TAZEWELL,24651,2769888714,NON-PROFIT,Yes,Yes,Yes,Yes,Yes,Yes,07/10/1985,3.5,-,407,427,95.3,-,114,248,46.0,-,270,292,87.3,-,278,289,91.1,-,279,292,90.7,-,263,277,91.4,-,278,290,88.3,-,0,300,0.0,-,424,427,99.3,-,8,427,1.9,-,201,290,69.31,-,-,-,-,The number of patient episodes for this measur...,288,288,100.00,-,161,202,79.70,85.72,79.76,90.54,Better Than National Rate,-,3,120,2.50,3.70,2.71,5.17,Same As National Rate,-,7,77,9.09,8.79,5.47,14.34,Same As National Rate,-,0.90,-,281
3,VA,497019,SENTARA HOME CARE SERVICES,"154 HANSEN ROAD, SUITE 101",CHARLOTTESVILLE,22911,4346542900,NON-PROFIT,Yes,Yes,Yes,Yes,Yes,Yes,07/03/1985,3,-,"1,530","1,787",85.6,-,828,"1,094",75.7,-,"1,287","1,462",83.9,-,"1,294","1,461",86.9,-,"1,340","1,461",88.4,-,"1,210","1,334",88.9,-,"1,255","1,452",81.1,-,6,"1,489",0.4,-,"1,755","1,793",97.9,-,17,"1,791",0.9,-,"1,134","1,454",77.99,-,92,105,87.62,-,"1,354","1,384",97.83,-,"1,647","1,968",83.69,87.74,85.85,89.66,Better Than National Rate,-,45,"1,256",3.58,3.86,3.08,5.06,Same As National Rate,-,55,986,5.58,5.72,4.68,7.10,Better Than National Rate,-,0.88,-,"2,547"
4,VA,497020,BUCHANAN GENERAL HOSPITAL HOME HEALTH AGENCY,"1535 SLATE CREEK ROAD, 5TH FLOOR",GRUNDY,24614,2769351509,NON-PROFIT,Yes,Yes,Yes,Yes,No,Yes,07/18/1985,2,-,237,237,100.0,-,76,134,56.7,-,106,157,69.4,-,60,154,56.6,-,105,156,68.3,-,61,120,55.9,-,44,94,58.4,-,0,162,0.0,-,237,237,100.0,-,0,237,0.0,-,97,158,61.39,-,-,-,-,The number of patient episodes for this measur...,156,157,99.36,-,56,97,57.73,61.93,50.74,70.42,Worse Than National Rate,-,6,52,11.54,4.37,2.92,6.48,Same As National Rate,-,10,57,17.54,11.27,7.46,16.27,Same As National Rate,-,0.93,-,120

In [4]:
print(f"Dataset shape: {df.shape}")

Dataset shape: (247, 96)

In [6]:
fairfax_cities = [
       'FAIRFAX', 'RESTON', 'VIENNA', 'MCLEAN', 'FALLS CHURCH', 
        'SPRINGFIELD', 'HERNDON', 'CENTREVILLE', 'CHANTILLY', 
        'BURKE', 'ANNANDALE', 'CLIFTON', 'OAKTON', 'GREAT FALLS',
        'LORTON', 'FAIRFAX STATION', 'MERRIFIELD', 'DUNN LORING',
        'TYSONS', 'TYSONS CORNER',
    ]

In [7]:
arlington_cities = [
        'ARLINGTON',
    ]

In [8]:
all_target_cities = fairfax_cities + arlington_cities
all_target_cities

['FAIRFAX',
 'RESTON',
 'VIENNA',
 'MCLEAN',
 'FALLS CHURCH',
 'SPRINGFIELD',
 'HERNDON',
 'CENTREVILLE',
 'CHANTILLY',
 'BURKE',
 'ANNANDALE',
 'CLIFTON',
 'OAKTON',
 'GREAT FALLS',
 'LORTON',
 'FAIRFAX STATION',
 'MERRIFIELD',
 'DUNN LORING',
 'TYSONS',
 'TYSONS CORNER',
 'ARLINGTON']

In [9]:
print(f"States in the dataset: {df['State'].unique()}")

States in the dataset: ['VA']

In [14]:
# Correct way to create va_df (without the comma)
va_df = df[df['State'] == 'VA']

In [15]:
target_counties_df = va_df[va_df['City/Town'].isin(all_target_cities)]
target_counties_df

,State,CMS Certification Number (CCN),Provider Name,Address,City/Town,ZIP Code,Telephone Number,Type of Ownership,Offers Nursing Care Services,Offers Physical Therapy Services,Offers Occupational Therapy Services,Offers Speech Pathology Services,Offers Medical Social Services,Offers Home Health Aide Services,Certification Date,Quality of patient care star rating,Footnote for quality of patient care star rating,Numerator for how often the home health team began their patients' care in a timely manner,Denominator for how often the home health team began their patients' care in a timely manner,How often the home health team began their patients' care in a timely manner,Footnote for how often the home health team began their patients' care in a timely manner,Numerator for how often the home health team determined whether patients received a flu shot for the current flu season,Denominator for how often the home health team determined whether patients received a flu shot for the current flu season,How often the home health team determined whether patients received a flu shot for the current flu season,Footnote for how often the home health team determined whether patients received a flu shot for the current flu season,Numerator for how often patients got better at walking or moving around,Denominator for how often patients got better at walking or moving around,How often patients got better at walking or moving around,Footnote for how often patients got better at walking or moving around,Numerator for how often patients got better at getting in and out of bed,Denominator for how often patients got better at getting in and out of bed,How often patients got better at getting in and out of bed,Footnote for how often patients got better at getting in and out of bed,Numerator for how often patients got better at bathing,Denominator for how often patients got better at bathing,How often patients got better at bathing,Footnote for how often patients got better at bathing,Numerator for how often patients' breathing improved,Denominator for how often patients' breathing improved,How often patients' breathing improved,Footnote for how often patients' breathing improved,Numerator for how often patients got better at taking their drugs correctly by mouth,Denominator for how often patients got better at taking their drugs correctly by mouth,How often patients got better at taking their drugs correctly by mouth,Footnote for how often patients got better at taking their drugs correctly by mouth,Numerator for Changes in skin integrity post-acute care: pressure ulcer/injury,Denominator for Changes in skin integrity post-acute care: pressure ulcer/injury,Changes in skin integrity post-acute care: pressure ulcer/injury,Footnote Changes in skin integrity post-acute care: pressure ulcer/injury,Numerator for how often physician-recommended actions to address medication issues were completely timely,Denominator for how often physician-recommended actions to address medication issues were completely timely,How often physician-recommended actions to address medication issues were completely timely,Footnote for how often physician-recommended actions to address medication issues were completely timely,Numerator for Percent of Residents Experiencing One or More Falls with Major Injury,Denominator for Percent of Residents Experiencing One or More Falls with Major Injury,Percent of Residents Experiencing One or More Falls with Major Injury,Footnote for Percent of Residents Experiencing One or More Falls with Major Injury,Numerator for Discharge Function Score,Denominator for Discharge Function Score,Discharge Function Score,Footnote for Discharge Function Score,Numerator for Transfer of Health Information to the Provider,Denominator for Transfer of Health Information to the Provider,Transfer of Health Information to the Provider,Footnote for Transfer of Health Information to the Provider,Numerator for Transfer of Health Information to the Patient,Denominator for Transfer of Health Information to the Patient,Transfer of Health Information to the Patient,Footnote for Transfer of Health Information to the Patient,DTC Numerator,DTC Denominator,DTC Observed Rate,DTC Risk-Standardized Rate,DTC Risk-Standardized Rate (Lower Limit),DTC Risk-Standardized Rate (Upper Limit),DTC Performance Categorization,Footnote for DTC Risk-Standardized Rate,PPR Numerator,PPR Denominator,PPR Observed Rate,PPR Risk-Standardized Rate,PPR Risk-Standardized Rate (Lower Limit),PPR Risk-Standardized Rate (Upper Limit),PPR Performance Categorization,Footnote for PPR Risk-Standardized Rate,PPH Numerator,PPH Denominator,PPH Observed Rate,PPH Risk-Standardized Rate,PPH Risk-Standardized Rate (Lower Limit),PPH Risk-Standardized Rate (Upper Limit),PPH Performance Categorization,Footnote for PPH Risk-Standardized Rate,"How much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally","Footnote for how much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally","No. of episodes to calc how much Medicare spends per episode of care at agency, compared to spending at all agencies (national)"
0,VA,497008,INOVA HOME HEALTH LLC,9900 MAIN STREET - SUITE 100,FAIRFAX,22031,5714323100,PROPRIETARY,Yes,Yes,Yes,Yes,No,Yes,10/01/1976,4,-,"4,046","4,492",90.1,-,"1,712","2,774",61.7,-,"3,015","3,230",91.8,-,"3,066","3,221",93.6,-,"3,098","3,228",94.4,-,"1,890","1,943",98.8,-,"3,026","3,189",92.2,-,3,"3,341",0.2,-,"3,959","4,495",88.1,-,22,"4,464",0.5,-,"2,173","3,227",67.34,-,212,270,78.52,-,"2,546","3,071",82.90,-,"2,851","4,299",66.32,71.48,69.69,72.96,Worse Than National Rate,-,98,"3,359",2.92,3.36,2.85,3.90,Same As National Rate,-,240,"1,843",13.02,10.76,9.57,11.78,Same As National Rate,-,0.98,-,"6,276"
11,VA,497033,THE MEDICAL TEAM INC,1896 PRESTON WHITE DRIVE,RESTON,20191,7033902300,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,09/27/1985,3.5,-,483,484,99.8,-,237,324,73.1,-,301,361,80.8,-,320,361,85.5,-,312,361,83.6,-,268,308,85.8,-,286,358,76.9,-,2,371,0.4,-,480,484,99.2,-,3,483,0.6,-,253,360,70.28,-,50,54,92.59,-,315,317,99.37,-,423,541,78.19,84.88,81.90,87.68,Better Than National Rate,-,14,277,5.05,4.18,3.11,5.41,Same As National Rate,-,18,279,6.45,6.47,4.61,9.16,Better Than National Rate,-,0.95,-,725
27,VA,497255,"AMERICARE IN HOME NURSING, HOME RECOVERY",6225 BRANDON AVENUE SUITE 440,SPRINGFIELD,22150,7039122080,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,04/09/1981,4.5,-,249,251,99.2,-,113,162,69.8,-,193,198,93.4,-,194,198,94.9,-,191,198,95.1,-,162,167,95.3,-,182,185,93.5,-,0,201,0.0,-,246,251,98.0,-,2,251,0.8,-,162,198,81.82,-,24,38,63.16,-,121,162,74.69,-,220,257,85.60,84.45,80.04,87.98,Better Than National Rate,-,4,91,4.40,4.05,2.84,5.88,Same As National Rate,-,9,148,6.08,8.70,5.19,14.38,Same As National Rate,-,0.97,-,310
62,VA,497478,"CARING NURSES ADVOCATES FOR PATIENTS, LTD",10875 MAIN STREET SUITE 201,FAIRFAX,22030,5714320230,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,06/23/1994,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,5,-,-,-,-,Not Available,The number of patient episodes for this measur...,-,3,-,-,-,-,Not Available,The number of patient episodes for this measur...,-,3,-,-,-,-,Not Available,The number of patient episodes for this measur...,-,The number of patient episodes for this measur...,12
63,VA,497485,ENHABIT HOME HEALTH (RESTON),12355 SUNRISE VALLEY DRIVE SUITE 230,RESTON,20191,8047039927,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,12/29/1994,3.5,-,712,718,99.2,-,342,447,76.5,-,473,534,88.4,-,484,531,90.3,-,473,534,92.1,-,286,343,89.3,-,442,517,86.7,-,0,574,0.0,-,708,718,98.6,-,11,712,1.5,-,404,535,75.51,-,14,34,41.18,-,462,540,85.56,-,848,998,84.97,84.29,82.70,86.08,Better Than National Rate,-,34,993,3.42,4.22,3.29,5.47,Same As National Rate,-,36,385,9.35,11.06,8.26,14.89,Same As National Rate,-,0.96,-,"1,295"
69,VA,497502,"PROFESSIONAL HEALTHCARE RESOURCES, INC","7619 LITTLE RIVER TURNPIKE, SUITE 600",ANNANDALE,22003,7037528760,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,09/06/1995,3,-,83,83,100.0,-,43,47,91.5,-,49,66,71.7,-,59,66,86.2,-,52,66,78.8,-,44,45,100.0,-,49,65,77.8,-,0,67,0.0,-,75,83,90.4,-,0,83,0.0,-,44,66,66.67,-,-,-,-,The number of patient episodes for this measur...,45,56,80.36,-,70,90,77.78,80.91,72.34,88.41,Same As National Rate,-,3,47,6.38,4.06,2.84,5.77,Same As National Rate,-,8,56,14.29,12.66,7.54,19.86,Same As National Rate,-,1.02,-,135
74,VA,497536,AMERICAN HEALTH CARE PROFESSIONALS,"752 WALKER ROAD, SUITE E",GREAT FALLS,22066,7033882813,PROPRIETARY,Yes,Yes,Yes,No,No,Yes,02/10/1997,3,-,31,33,93.9,-,-,-,-,The number of patient episodes for this measur...,16,27,75.7,-,15,27,75.5,-,21,26,95.6,-,-,-,-,The number of patient episodes for this measur...,16,21,88.5,-,0,27,0.0,-,31,33,93.9,-,1,33,3.0,-,20,27,74.07,-,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,37,46,80.43,81.91,73.81,92.60,Same As National Rate,-,-,14,-,-,-,-,Not Available,The number of patient episodes for this measur...,3,30,10.00,10.45,5.63,19.70,Same As National Rate,-,0.97,-,79
79,VA,497547,CONTINUUM PEDIATRIC NURSING SERVICES,8230 LEESBURG PIKE SUITE 740,VIENNA,22182,7035060123,PROPRIETARY,Yes,No,Yes,No,No,No,08/13/1998,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,This measure currently does not have data or p...,-
82,VA,497550,MEDSTAR HEALTH HOME CARE,4040 NORTH FAIRFAX DRIVE - SUITE 625,ARLINGTON,22203,7037481533,NON-PROFIT,Yes,Yes,Yes,No,No,Yes,07/24/1998,3.5,-,243,255,95.3,-,132,162,81.5,-,178,208,86.1,-,193,208,92.4,-,181,209,86.7,-,117,139,89.9,-,167,196,84.9,-,0,211,0.0,-,246,255,96.5,-,2,254,0.8,-,176,208,84.62,-,-,-,-,The number of patient episodes for this measur...,194,199,97.49,-,234,298,78.52,78.68,73.12,82.17,Same As National Rate,-,3,218,1.38,3.59,2.53,5.57,Same As National Rate,-,13,147,8.84,9.72,6.38,13.75,Same As National Rate,-,1.05,-,407
83,VA,497552,HUMAN TOUCH HOME HEALTH CARE,"113 PARK AVENUE, SUITE 300",FALLS CHURCH,22046,7035310540,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,12/23/1998,3,-,304,307,99.0,-,169,175,96.6,-,230,270,81.3,-,247,270,86.1,-,231,270,84.4,-,172,198,88.7,-,233,269,81.0,-,1,270,0.4,-,307,307,100.0,-,1,307,0.3,-,195,269,72.49,-,10,25,40.00,-,232,244,95.08,-,67,82,81.71,82.65,72.21,89.59,Same As National Rate,-,2,42,4.76,3.99,2.80,5.60,Same As National Rate,-,1,32,3.12,8.25,4.64,14.54,Same As National Rate,-,0.84,-,132
85,VA,497559,"CAREGIVERS HOME HEALTH SERVICES, INC","8500 LEESBURG PIKE, SUITE 500",TYSONS,22182,7035326210,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,11/08/1999,3.5,-,"3,699","3,701",99.9,-,"2,005","2,298",87.2,-,"2,267","2,519",87.3,-,"2,319","2,517",89.4,-,"2,294","2,519",91.9,-,"2,387","2,523",90.8,-,"2,329","2,497",89.6,-,5,"2,586",0.0,-,"3,671","3,702",99.2,-,27,"3,700",0.7,-,"1,948","2,517",77.39,-,147,168,87.50,-,"2,348","2,412",97.35,-,"1,624","2,277",71.32,73.95,72.47,75.49,Worse Than National Rate,-,54,"1,464",3.69,4.27,3.52,5.23,Same As National Rate,-,137,"1,017",13.47,13.81,11.70,15.99,Worse Than National Rate,-,0.97,-,"3,411"
90,VA,497568,ESPRIT HOME HEALTHCARE LLC,4209 EVERGREEN LANE SUITE 101,ANNANDALE,22003,7039987400,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,03/22/2001,4.5,-,200,200,100.0,-,133,136,97.8,-,147,158,90.9,-,151,158,92.5,-,144,158,92.8,-,148,150,97.2,-,149,158,91.9,-,0,158,0.0,-,199,200,99.5,-,1,200,0.5,-,116,158,73.42,-,14,30,46.67,-,118,128,92.19,-,245,313,78.27,79.15,75.14,83.00,Same As National Rate,-,6,128,4.69,4.03,2.88,5.85,Same As National Rate,-,7,160,4.38,6.70,4.19,10.50,Same As National Rate,-,0.94,-,551
92,VA,497570,ENHABIT HOME HEALTH,5501 BACKLICK ROAD STE 250,SPRINGFIELD,22151,7035501400,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,12/27/2001,2,-,420,604,69.5,-,216,352,61.4,-,323,458,71.6,-,361,453,79.3,-,335,459,75.1,-,139,163,90.5,-,290,444,70.4,-,0,483,0.0,-,570,604,94.4,-,8,592,1.4,-,284,458,62.01,-,42,59,71.19,-,383,424,90.33,-,614,755,81.32,81.51,78.31,83.67,Better Than National Rate,-,7,455,1.54,3.22,2.37,4.16,Same As National Rate,-,22,323,6.81,8.37,6.11,10.96,Same As National Rate,-,0.96,-,"1,147"
96,VA,497574,INTERIM HEALTHCARE,10340 DEMOCRACY LN,FAIRFAX,22030,2762002606,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,05/23/2002,2,-,25,28,89.3,-,-,-,-,The number of patient episodes for this measur...,14,22,64.2,-,14,22,62.4,-,17,22,73.9,-,-,-,-,The number of patient episodes for this measur...,14,20,66.0,-,0,22,0.0,-,27,28,96.4,-,0,28,0.0,-,9,22,40.91,-,-,-,-,The number of patient episodes for this measur...,19,20,95.00,-,53,72,73.61,76.10,66.30,84.79,Same As National Rate,-,0,29,0.00,3.70,2.41,5.17,Same As National Rate,-,2,28,7.14,9.53,5.14,18.97,Same As National Rate,-,0.95,-,123
97,VA,497577,AVEANNA HEALTHCARE,"3554 CHAIN BRIDGE RD, STE 103",FAIRFAX,22030,7038737672,PROPRIETARY,Yes,Yes,Yes,Yes,No,No,02/05/2003,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,This measure currently does not have data or p...,-
103,VA,497587,NATIONAL HOME HEALTH CARE INC,"459 HERNDON PARKWAY, SUITE 17",HERNDON,20170,7037873060,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,02/06/2004,3,-,967,"1,038",93.2,-,477,608,78.5,-,528,737,84.8,-,548,725,87.5,-,556,740,83.8,-,350,409,96.0,-,402,642,79.5,-,2,777,0.2,-,939,"1,039",90.4,-,19,"1,027",1.9,-,440,745,59.06,-,132,184,71.74,-,536,593,90.39,-,"1,214","1,606",75.59,79.81,77.49,81.56,Better Than National Rate,-,34,814,4.18,4.29,3.46,5.49,Same As National Rate,-,60,748,8.02,8.05,6.33,10.16,Same As National Rate,-,0.97,-,"2,412"
107,VA,497596,GREENSPRING VILLAGE HOME SUPPORT SERVICES,7410 SPRING VILLAGE DRIVE,SPRINGFIELD,22150,7039233123,NON-PROFIT,Yes,Yes,Yes,Yes,Yes,Yes,03/24/2005,3,-,271,280,96.8,-,171,178,96.1,-,186,215,85.3,-,194,215,91.4,-,196,215,89.0,-,159,203,77.2,-,158,214,72.7,-,0,220,0.0,-,252,280,90.0,-,2,277,0.7,-,178,213,83.57,-,-,-,-,The number of patient episodes for this measur...,203,206,98.54,-,244,305,80.00,90.53,86.06,95.16,Better Than National Rate,-,6,178,3.37,3.72,2.68,5.26,Same As National Rate,-,14,172,8.14,8.50,5.72,11.76,Same As National Rate,-,1.09,-,399
115,VA,497605,VIRGINIA HEALTHCARE SERVICES,"7010 LITTLE RIVER TURNPIKE, SUITE 400",ANNANDALE,22003,7033335288,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,12/20/2005,3.5,-,"1,638","1,638",100.0,-,879,"1,044",84.2,-,"1,106","1,265",84.5,-,"1,085","1,264",85.4,-,"1,086","1,269",86.0,-,642,789,83.8,-,"1,058","1,258",79.6,-,3,"1,300",0.3,-,"1,619","1,638",98.8,-,7,"1,638",0.4,-,944,"1,280",73.75,-,115,171,67.25,-,"1,051","1,120",93.84,-,154,208,74.04,74.27,68.35,79.40,Same As National Rate,-,4,88,4.55,4.03,2.80,5.83,Same As National Rate,-,5,97,5.15,8.41,5.06,13.16,Same As National Rate,-,0.83,-,431
119,VA,497616,HOME RECOVERY,6225 BRANDON AVE SUITE 440B,SPRINGFIELD,22150,7034811919,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,10/24/2006,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,The number of patient episodes for this measur...,-,-,-,This measure currently does not have data or p...,-,-,-,The number of patient episodes for this measur...,-,2,-,-,-,-,Not Available,The number of patient episodes for this measur...,-,4,-,-,-,-,Not Available,The number of patient episodes for this measur...,-,-,-,-,-,-,-,This measure currently does not have data or p...,-,The number of patient episodes for this measur...,2
123,VA,497626,"SHEME HOME HEALTHCARE AGENCY, INC","4024 WILLIAMSBURG CT, FIRST FLOOR",FAIRFAX,22032,7032780081,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,05/17/2007,3,-,95,96,99.0,-,64,65,98.5,-,45,64,75.7,-,48,64,80.8,-,50,64,85.1,-,47,54,91.1,-,38,61,76.8,-,0,65,0.0,-,96,96,100.0,-,1,96,1.0,-,26,62,41.94,-,20,24,83.33,-,37,41,90.24,-,78,105,74.29,74.68,66.61,80.34,Same As National Rate,-,0,21,0.00,3.75,2.47,5.52,Same As National Rate,-,4,61,6.56,9.31,4.52,14.86,Same As National Rate,-,0.90,-,335
125,VA,497636,"PAVILION MEDICAL HOME CARE & STAFFING, LLC","4115 ANNANDALE ROAD, SUITE 202",ANNANDALE,22003,7032999898,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,04/01/2008,4,-,271,302,89.7,-,130,161,80.7,-,211,232,91.5,-,193,230,85.4,-,205,230,91.4,-,183,186,98.7,-,205,223,93.6,-,0,236,0.0,-,271,305,88.9,-,0,305,0.0,-,152,234,64.96,-,62,102,60.78,-,62,134,46.27,-,337,474,71.10,77.95,74.16,81.95,Same As National Rate,-,20,316,6.33,4.56,3.39,5.93,Same As National Rate,-,20,222,9.01,8.71,6.00,12.11,Same As National Rate,-,0.93,-,746
126,VA,497638,REVIVAL HOMECARE AGENCY,5101C BACKLICK ROAD,ANNANDALE,22003,7033416670,PROPRIETARY,Yes,Yes,Yes,Yes,Yes,Yes,09/16/2008,3.5,-,262,301,87.0,-,155,170,91.2,-,223,238,92.4,-,216,237,88.3,-,222,239,92.3,-,220,228,93.9,-,214,238,89.5,-,0,244,0.0,-,296,301,98.3,-,1,299,0.3,-,150,238,63.03,-,55,71,77.46,-,148,173,85.55,-,182,235,77.45,80.90,76.34,85.53,Better Than National Rate,-,2,123,1.63,3.65,2.48,5.38,Same As National Rate,-,6,76,7.89,9.23,5.29,14.24,Same As National Rate,-,0.91,-,407

In [17]:
# Optional: Save the filtered dataset to a new CSV file
target_counties_df.to_csv('./va_HomeHealthCare.csv', index=False)